[package]
name = "golion-optimization"
version = "0.0.0"
edition = "2024"

[dependencies]
# -- Optimization Modeler
good_lp = { version = "1.15.1", features = ["highs"], default-features = false }
# -- Workspace
golion-domain = { workspace = true }
# Others
derive_more = { workspace = true }
jiff = { workspace = true }
uuid = { workspace = true }
itertools = "0.15.0"

[lints]
workspace = true
