[package]
name = "golion-optimization"
version = "0.0.0"
edition = "2024"

[dependencies]
derive_more = { workspace = true }
golion-domain = { workspace = true }
good_lp = { version = "1.15.1", features = ["highs"], default-features = false }
jiff = { workspace = true }
uuid = "1.23.1"

[lints]
workspace = true
