mod error;
mod highs;
pub mod market;
pub mod model;
pub mod perimeter;
pub mod physical;
mod support;
pub use self::error::{Error, Result};
pub use self::highs::HighsOptimizer;
pub use self::model::Model;
