[package]
name = "golion-server"
version = "0.0.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
golion-contract = { workspace = true }
golion-optimization = { workspace = true}
golion-domain = { workspace = true}
jiff = "0.2.35"

[lints]
workspace = true

[dev-dependencies]
anyhow = "1"
httpc-test = "0.1.10"
