[package]
name = "golion-server"
version = "0.0.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
tokio = { version = "1", features = ["full"] }
golion-domain = { version = "0.0.0", path = "../golion-domain" }
golion-optimization = { version = "0.0.0", path = "../golion-optimization" }

[lints]
workspace = true

[dev-dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
httpc-test = "0.1.10"
serde_json = "1"
