[package]
name = "golion-contract"
version = "0.0.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.44", features = ["serde"] }
uuid = { version = "1.23.1", features = ["serde", "v4"] }
garde = { version = "0.22.1", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
golion-common = { workspace = true, features = ["serde"] }
thiserror = "2.0.18"
typed-builder = "0.23.2"
[lints]
workspace = true
