[package]
name = "golion-contract"
version = "0.0.0"
edition = "2024"

[dependencies]
derive_more = { workspace = true }
garde = { version = "0.23", features = ["derive"] }
golion-domain = { workspace = true }
jiff = { workspace = true, features = ["serde"] }
serde = { workspace = true }
thiserror = "2.0.18"
typed-builder = "0.23.2"
uuid = { version = "1.23.1", features = ["serde", "v4"] }

[lints]
workspace = true
