name: Prek checks
on: [push, pull_request]

permissions:
  contents: read

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6.2
        with:
          persist-credentials: false
      - uses: j178/prek-action@6ad80277337ad479fe43bd70701c3f7f8aa74db3 # v2
        with:
          prek-version: "0.3.11"
